// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DEEP-backend-image/database/ent/image"
	"DEEP-backend-image/database/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescInstance is the schema descriptor for instance field.
	imageDescInstance := imageFields[1].Descriptor()
	// image.InstanceValidator is a validator for the "instance" field. It is called by the builders before save.
	image.InstanceValidator = imageDescInstance.Validators[0].(func([]byte) error)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() uuid.UUID)
}
